### ISSUE TITLE
Add some "loading" feedback for the user when validating an offer

### ISSUE THREAD

**Issue by chahuistle** [qbicsoftware/qoffer-portlet#13]
Whenever the "Validate" button is pressed, a lengthy process occurs on the background.

It would be nice to let the user know that the file is being downloaded. The easiest implementation would be to disable the "Validate" button, change its label to "Validating...", change the pointer to a sandclock or something similar, then, after verification finished, all goes back to normal (pointer goes back to default, label reverts to "Validate" and the button is enabled).

The fancy implementation would be to use a transluscent overlay with the text "Please wait". This overlay would prevent users clicking somewhere on the controls.

**Comment by jenniferboedker** [comment]
Is implemented with #18 by a modal window
