### ISSUE TITLE
Disable the "Download" button every time a change in the model is done

### ISSUE THREAD

**Issue by chahuistle** [qbicsoftware/qoffer-portlet#16]
The "Download" button should be deactivated every time that one of these things happen:

1. The user clicks on an offer (upper grid in "Offer Manager" tab).
1. The user changes anything on the packages (lower grid in "Offer Manager" tab).

**Comment by jenniferboedker** [comment]
Furthermore, the "Validate" Button is disabled while an offer is validated.
