### ISSUE TITLE
Detailed cost information must be displayed on the generated offer

### ISSUE THREAD

**Issue by chahuistle** [qbicsoftware/qoffer-portlet#17]
Detailed cost information for individual work packages (listed by internal package IDs) can be found on the second page. This should be found under the "Total Amount" in the generated file.

**Comment by jenniferboedker** [comment]
The Template.docx is updated (`YYYYMMDD_PiName_QXXXX_TEMPLATE_FINAL_bound_UPDATE.docx`)
