### ISSUE TITLE
Formatting Error for Prices

### ISSUE THREAD

**Issue by jenniferboedker** [qbicsoftware/qoffer-portlet#22]
When a price like 10.000€ is entered qOffer reads it as 10,000€ where the comma indicates the separation between Euro and Cents. 
In the generated offer the price also has a wrong format and the final sum could look like e.g. 183.600€ where this is the german notation but was entered in english notation.

**Comment by jenniferboedker** [comment]
The problem occurred because of unsuitable datatypes in the database. They have been changed from FLOAT to DECIMAL(11,2) for each column that represents a price (see [here](https://stackoverflow.com/questions/4397302/what-mysql-type-is-most-suitable-for-price-column)). In the code the queries had to be changed accordingly.
Further problems have been noticed that might occurred through these changes:

1. The discount is not correctly applied.

2. When updating a price (like the internal price for a package) in the _PackageManagerTab_ it is not updated in the _OfferManagerTab_ for the offers that use that package. Also the total price for offers using that Package is not updated.

**Comment by subwaystation** [comment]
One possible error we suspect is that we did not change all FLOATs to DECIMALs in the code. Maybe @jenniferboedker you can inspect that further?

**Comment by jenniferboedker** [comment]
Solved with #26
